# Generated by Django 3.1 on 2020-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldescitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
